global using System;
global using System.Text;
global using System.Text.RegularExpressions;
global using System.Threading;
global using NUnit.Framework;
global using OpenQA.Selenium;
global using OpenQA.Selenium.Edge;
global using OpenQA.Selenium.Support.UI;
global using OpenQA.Selenium.Chrome;